### ISSUE TITLE
English Language

### ISSUE THREAD

**Issue by ChrisChinchilla** [sitepoint-editors/peer-review-docs#4]
https://github.com/sitepoint-editors/peer-review-docs/blob/master/SUBMITTING.md#english-language

States "Please don't expect reviewers to fix your language".

I'm unsure about this. Especially as I know I will be the sole reviewer for a while. If I didn't allow articles with bad English that needed work I would have very few submissions. Sad, but very true.

I have had quite a few submissions with bad English but good content, so I work through them. There are of course many that are just plain **bad**. Maybe we could soften this sentence somehow?

**Comment by Swader** [comment]
Softened, hopefully. See how it feels and let me know? If you think it's OK I'll put the changes live

**Comment by ChrisChinchilla** [comment]
Much better @Swader :)
