### ISSUE TITLE
'Literally'

### ISSUE THREAD

**Issue by ChrisChinchilla** [sitepoint-editors/peer-review-docs#6]
I literally hate the word literally…

https://github.com/sitepoint-editors/peer-review-docs/blob/master/PEER-REVIEW.md#are-you-trying-to-get-us-to-do-editors-jobs-for-you

Personal @Swader up to you ;)

**Comment by Swader** [comment]
Haha, I prefer it in this case so, overruled :P

**Comment by ChrisChinchilla** [comment]
WHAAAT @Swader ! I will literally pour a beer over you next time I see you ;)

**Comment by jameshibbard** [comment]
Such a waste of good beer.

**Comment by Swader** [comment]
Haha, you do that but make sure my mouth is open and facing upwards first!

## 

Bruno Skvorc
PHP editor, SitePoint.com
Devangelist, Diffbot.com

Twitter: @bitfalls http://www.twitter.com/bitfalls
G+: google.com/+BrunoSkvorc
Skype: bruno.skvorc
